apiVersion: v1
kind: ConfigMap
metadata:
  name: simavi-config-map-hesse
data:
  kafkastore_bootstrap_servers: 'sphinx-kafka-evora-kafka-bootstrap.cip-evora.svc:9092'
  email_username: 'id@sphinxproject.com'
  email_password: 'test123$'
  smtp_host: 'sphinx-smtp-service'
  smtp_port: '2525'
  tls_enabled: 'false'
  smtp_auth: 'false'
  smtp_debug: 'true'
  factory_class: 'javax.net.ssl.SSLSocketFactory'
  factory_fallback: 'true'
  trust_all_hosts: 'true'
  kafka_properties_security_protocol: PLAINTEXT
  kafka_properties_sasl_mechanism: ANONYMOUS
  oauth_token_endpoint_uri: "http://evora.172.26.7.181.nip.io/SMPlatform/manager/rst/KafkaAuthentication"
  ssl_truststore_path: file:/jks/sphinx_hesse.jks
  dtm_instance_key: '4234567'
  spring_datasource_url: jdbc:postgresql://146.124.106.182:30007/sphinx
  elasticsearch_url: "http://elasticsearch-simavi-evora:80"
  exclude_ips_suricata: '' 
  exclude_ips_tshark: ''
  sm_ip: "http://evora.172.26.7.181.nip.io/SMPlatform/manager/rst/"
  source: 'ens192'
  kafka_jks: sphinx_hesse.jks
  file_jks: /jks/sphinx_polaris.jks
  sftp_host: 10.10.2.65
  sftp_port: '22'
  sftp_password: 'sphinxfdce'
  sftp_username: 'sphinxfdce'
  sftp_upload_directory: '/home/sphinxfdce/fdce_imported_data'
  topic_dss: 'dss-dtm-record-traffic'
  hbase_zookeeper: 'sphinx-hbase-hesse:2181'
  react_app_sphinx_sso_api_url: "//evora.146.124.106.181.nip.io/SMPlatform/manager/rst"
  gf_sphinx_sm_base_url: "http://service-manager.cip-evora.svc:8080/SMPlatform/manager/rst"
  
  
