## GRAFANA INTERACTIVE DASHBOARDS PersistentVolume Claim ##
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: interactive-dashboards-pv-claim-hese
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
## GRAFANA INTERACTIVE DASHBOARDS Deployment ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: interactive-dashboards
  name: interactive-dashboards-deployment-hesse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interactive-dashboards
  template:
    metadata:
      labels:
        app: interactive-dashboards
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana-dashboards-hesse
          image: registry.sphinx-repo.intracom-telecom.com/sphinx-project/interactive-dashboards/grafana/grafana_dashboards
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http-grafana-hs
              protocol: TCP
          env:
            - name: GF_SERVER_DOMAIN
              value: evora.146.124.106.181.nip.io
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/interactive-dashboards/"
#                value: "https://sphinx-kubernetes.intracom-telecom.com/interactive-dashboards/"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SECURITY_COOKIE_SAMESITE
              value: "disabled"
            - name: GF_SPHINX_SM_BASE_URL
              value: "http://service-manager.cip-evora.svc:8080/SMPlatform/manager/rst"
            - name: GF_SMTP_HOST
              #value: "smtp.gmail.com:465"
              value: "smtp.gmail.com:587"
            - name: GF_SMTP_ENABLED
              value: "true"
            - name: GF_SMTP_USER
              value: "sphinxidalerting@gmail.com"
            - name: GF_SMTP_PASSWORD
              value: "grafana2021"
            - name: GF_SMTP_FROM_ADDRESS
              value: "sphinxidalerting@gmail.com"
            - name: GF_SMTP_FROM_NAME
              value: "Interactive Dashboards"
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: GF_ANALYTICS_CHECK_FOR_UPDATES
              value: "false"
            - name: GF_PANELS_DISABLE_SANITIZE_HTML
              value: "true"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          #resources:
          #  requests:
          #    cpu: 250m
          #    memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv-hese
            - mountPath: /etc/grafana/provisioning/datasources/
              name: grafana-datasources
      volumes:
        - name: grafana-pv-hese
          persistentVolumeClaim:
            claimName: interactive-dashboards-pv-claim-hese
        - name: grafana-datasources
          persistentVolumeClaim:
            claimName: interactive-dashboards-config-pv-claim-hese
      imagePullSecrets:
          - name: intracom-repository
## GRAFANA INTERACTIVE DASHBOARDS Service ##
---
apiVersion: v1
kind: Service
metadata:
  name: interactive-dashboards
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana-hs
  selector:
    app: interactive-dashboards
  sessionAffinity: None
  type: ClusterIP
