{
 "title": "Ecare Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ecare nonvalidated chart",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "string", "label": "Records" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUBSTRING(\"START_NONVALIDATED\", 0, 11) as time,\r\n  COUNT(\"UUID\") AS \"Number of records\"\r\nFROM\r\n  \"kafka_ECARE_NONVALIDATED_AVRO\"\r\nGROUP BY ((SUBSTRING(\"START_NONVALIDATED\", 0, 11)))\r\nORDER BY (SUBSTRING(\"START_NONVALIDATED\", 0, 11));\r\n"
    }
   ]
  },
  {
   "title": "Ecare nonvalidated",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"kafka_ECARE_NONVALIDATED_AVRO\"\nWHERE \"START_NONVALIDATED\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds});;"
    }
   ]
  },
  {
   "title": "Ecare bruteforce (UNFILTERED BY TIME)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"kafka_ECARE_BRUTEFORCE_AVRO\";"
    }
   ]
  },
  {
   "title": "Ecare login failures (UNFILTERED BY TIME)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT * FROM \"kafka_ECARE_LOGIN_FAILURES_AVRO\";"
    }
   ]
  }
 ]
}