{
 "title": "Honeypot",
 "tags": [
  "Honeypot",
  "HP"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "honey",
    "label": "Select Honeypot",
    "query": "select DISTINCT \"HONEYNAME\" from \"kafka_HP_MOST_USED_AVRO\" UNION SELECT DISTINCT \"NAME\" FROM \"kafka_HP_CURRENTLY_CONNECTED_IPS_AVRO\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding-top: 20px;\">\r\n    <p style=\"font-size: 55px; text-align: center;\"><b style=\"color: #00a79d;\">SPHINX</b> - Honeypot</p>\r\n    <hr>\r\n    <div style=\"text-align: center;\">\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/HP/HP_DASHBOARD_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Dashboard manual</a>\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/HP/HP_COMPONENT_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Component manual</a>\r\n    </div>\r\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:437",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:435", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Functionalities",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\n<h2>Short description</h2>\n<p style=\"text-align: justify\">SPHINX Honeypots aim to lure the attackers in using their provided services and learn from their \nattacks, in order to afterwards modify and deploy the necessary security controls that will address the \ndetected attacks. To achieve this, SPHINX HPs emulate commonly used services/protocols to serve an \nattractive for exploitation system to the cyber attackers.</p>\n<hr/>\n<h2>Objectives</h2>\n<ul style=\"list-style-type: none; padding: 0; margin: 0;\">\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green;font-size:20px;font-weight:bold;\">*</span> Emulate commonly used services/protocols</li>\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green;font-size:20px;font-weight:bold;\">*</span> Gather attack information from the intruders</li>\n</ul>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Status</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 5, "y": 6 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\"> Services </p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 6 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Info</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  CASE WHEN \"ISACTIVE\" = 'true' THEN 1 ELSE 0 END as active\r\nFROM \"kafka_HP_STATIC_INFO_AVRO\"\r\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\r\nORDER BY 1\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "SSH",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"STAT\"\nFROM \"kafka_HP_SERVICE_COUNTERS_AVRO\"\nwhere \"NAME\" = 'ssh'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"STAT\"\nFROM \"kafka_HP_SERVICE_COUNTERS_AVRO\"\nwhere \"NAME\" = 'http'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "title": "Honeypot Name",
   "type": "table",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"NAME\"\nFROM \"kafka_HP_STATIC_INFO_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\norder by \"TS\" desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "SMTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"STAT\"\nFROM \"kafka_HP_SERVICE_COUNTERS_AVRO\"\nwhere \"NAME\" = 'smtp'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "title": "FTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"STAT\"\nFROM \"kafka_HP_SERVICE_COUNTERS_AVRO\"\nwhere \"NAME\" = 'ftp'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "title": "Honeypot",
   "type": "table",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \"FLAVOUR\"\nFROM \"kafka_HP_STATIC_INFO_AVRO\"\nWHERE  \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\norder by \"TS\" desc\nlimit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 12 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\"> Attack Source Map </p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 2, "w": 9, "x": 15, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \"GENERALINFO\"\nFROM \"kafka_HP_STATIC_INFO_AVRO\"\nWHERE  \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\norder by \"TS\" desc\nlimit 1;"
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 14 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  extract(EPOCH from timestamp::timestamp) as time_sec,\n  ip_country as country,\n  ip_address as value,\n  lat as latitude,\n  long as longitude\nFROM hp_geoip\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY timestamp ASC;"
    }
   ]
  },
  {
   "title": "CPU Activity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"NAME\" AS metric,\n  \"CPUACTIVITYVAL\"\nFROM \"kafka_HP_INTERVAL_INFO_AVRO\"\nWHERE  \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nlimit 1;"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"NAME\" AS metric,\n  \"MEMORYUSAGEVAL\"\nFROM \"kafka_HP_INTERVAL_INFO_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nlimit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #141619; color: white; font-size: 20px; padding: 30px;\">Network Activity</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"UPLOADVAL\", \"UPLOADUNIT\"\nFROM \"kafka_HP_INTERVAL_INFO_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"DOWNLOADVAL\", \"DOWNLOADUNIT\"\nFROM \"kafka_HP_INTERVAL_INFO_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"DBUSAGE\"\nFROM \"kafka_HP_INTERVAL_INFO_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY 1\nlimit 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 27 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Currently Connected</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 27 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Most used Usernames</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 27 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Most used Passwords</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (\"IP\") \"IP\", \"SERVICE\"\nFROM \"kafka_HP_CURRENTLY_CONNECTED_IPS_AVRO\"\nWHERE \"NAME\" = '$honey'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY \"IP\", \"TS\" desc\nlimit 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (\"USERNAME\") \"USERNAME\", \"UTIMES\" as \"TIMES\"\nFROM \"kafka_HP_MOST_USED_AVRO\"\nWHERE \"HONEYNAME\" = '$honey'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY \"USERNAME\", \"TS\" desc\nlimit 10;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (\"PASSWORD\") \"PASSWORD\", \"PTIMES\" as \"TIMES\"\nFROM \"kafka_HP_MOST_USED_AVRO\"\nWHERE \"HONEYNAME\" = '$honey'\nAND \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY \"PASSWORD\", \"TS\" desc\nlimit 10;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 },
   "options": {
    "content": "<p style=\"text-align: center; background-color: #00a79d; color: white; font-size: 20px; padding: 10px;\">Captured IPs</p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT \"IP\"\nFROM \"kafka_HP_CAPTURED_IPS_AVRO\"\nWHERE \"TS\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nORDER BY \"IP\", \"TS\" desc\nlimit 10;"
    }
   ]
  }
 ]
}