version: "3"
services:
    sphinx-postgres:
        build: ./postgres
        environment:
            POSTGRES_DB: sphinx
            POSTGRES_USER: sphinx
            POSTGRES_PASSWORD: sphinx
        container_name: sphinx-postgres
        ports:
            - 8432:5432
        networks:
           sphinx-network:
                ipv4_address: 172.18.0.2
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
         - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka:29092"
            JVM_OPTS: "-Xms32M -Xmx64M"
            SERVER_SERVLET_CONTEXTPATH: "/"
        depends_on:
         - "kafka"
        networks:
            sphinx-network:
                ipv4_address: 172.18.0.3
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
         - "2181:2181"
        networks:
            sphinx-network:
                ipv4_address: 172.18.0.9
    kafka:
        image: wurstmeister/kafka
        ports:
         - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LOG_RETENTION_HOURS: 1
            KAFKA_LOG_RETENTION_MS: 3600000
            KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            sphinx-network:
                ipv4_address: 172.18.0.8

networks:
   sphinx-network:
      external: true