## Secret ##
---
  apiVersion: v1
  kind: Secret
  metadata:
    name: intracom-repository
  type: kubernetes.io/dockerconfigjson
  data:
    .dockerconfigjson: ew0KICAgICAgICAiYXV0aHMiOiB7DQogICAgICAgICAgICAgICAgInJlZ2lzdHJ5LnNwaGlueC1yZXBvLmludHJhY29tLXRlbGVjb20uY29tIjogew0KICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiWkdGdWFXVnNZV052T2tSVmJXNWxlbVYxTVRJakpBPT0iDQogICAgICAgICAgICAgICAgfQ0KICAgICAgICB9LA0KICAgICAgICAiSHR0cEhlYWRlcnMiOiB7DQogICAgICAgICAgICAgICAgIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy44IChsaW51eCkiDQogICAgICAgIH0NCn0=
