{
 "title": "General Dashboard",
 "tags": [ "General Dashboard" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 65px; text-align: center; color: white;\">GENERAL DASHBOARD<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "sphinx-interactive-dashboard-login-plugin",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM sphinx.\"kafka_ID_ALERTS\" WHERE extract(EPOCH from \"TIMESTAMP\"::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    },
    {
     "rawSql": "SELECT COUNT(*) FROM sphinx.\"kafka_ID_ALERTS\" WHERE \"STATUS\" LIKE 'OPEN' AND extract(EPOCH from \"TIMESTAMP\"::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "type": "simavi-interactive-dashboard-alerts-plugin",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT id as \"ID\", alert_src_id AS \"SOURCE ALERT\", dss_alert_id AS \"DSS Suggestion ID\", suggestion_applied AS \"Suggestion (text)\", timestamp AS \"TIME\" FROM suggestions_applied;"
    },
    {
     "rawSql": "SELECT row_to_json(t) FROM (SELECT \"DESCRIPTION\", \"CLASSIFICATION\", \"TIMESTAMP\", \"LOCATION\", \"INDICATION\", \"TOOL\", \"STATUS\", \"ACTION\", \"DETAILS\", id, \"ALERTID\" FROM sphinx.\"kafka_ID_ALERTS\" WHERE \"TIMESTAMP\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds}) ORDER BY id Desc LIMIT 100) t;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 45px; text-align: center; color: white;\">List of internal dashboards<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 45px; text-align: center; color: white;\">Components' external GUI<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "dashlist",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(*) FROM vaaas_reports\nWHERE CAST(cvss_score AS DOUBLE PRECISION) > 7.5\nAND extract(EPOCH from assessment_date::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "type": "simavi-interactive-dashboard-tools-list-plugin",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "simavi-interactive-dashboard-tools-list-plugin",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "simavi-interactive-dashboard-tools-list-plugin",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "simavi-interactive-dashboard-tools-list-plugin",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 45px; text-align: center; color: white;\">Alerts status & suggestions applied<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts status evidence",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT id as \"ID\", email AS \"User e-mail\", alert_id AS \"Alert ID\", lastvalue AS \"Last status\", updatedvalue AS \"New status\", timestamp as \"Time\" FROM alerts_status_history WHERE extract(EPOCH from timestamp::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "title": "Suggestions applied",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT id as \"ID\", alert_src_id AS \"SOURCE ALERT\", dss_alert_id AS \"DSS Suggestion ID\", suggestion_applied AS \"Suggestion (text)\", timestamp AS \"Time\" FROM suggestions_applied WHERE extract(EPOCH from timestamp::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 59 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 45px; text-align: center; color: white;\">Analytic Engine<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 59 },
   "options": {
    "content": "<p style=\"background-color: green; font-size: 45px; text-align: center; color: white;\">Vulnerabilities (VAAAS)<p>\n<hr>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operational environment - Attacks",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      {
       "jsonPath": "$.operational_environment.attacks[*~]",
       "name": "Type of attacks"
      },
      {
       "jsonPath": "$.operational_environment.attacks[*]",
       "name": "Number of attacks"
      }
     ],
     "method": "GET",
     "params": [
      [
       "start_date",
       "${__from:date:YYYY-MM-DD}"
      ],
      [
       "end_date",
       "${__to:date:YYYY-MM-DD}"
      ]
     ]
    }
   ]
  },
  {
   "title": "Honeypot - Attacks",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 62 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.hp.attacks[*~]", "name": "Type of attacks" },
      { "jsonPath": "$.hp.attacks[*]", "name": "Number of attacks" }
     ],
     "method": "GET",
     "params": [
      [
       "start_date",
       "${__from:date:YYYY-MM-DD}"
      ],
      [
       "end_date",
       "${__to:date:YYYY-MM-DD}"
      ]
     ]
    }
   ]
  },
  {
   "title": "Low Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 62 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(*) FROM vaaas_reports\nWHERE CAST(\"cvss_score\" AS DOUBLE PRECISION) < 6\nAND extract(EPOCH from assessment_date::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "title": "Medium Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 62 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(*) FROM vaaas_reports\nWHERE CAST(cvss_score AS DOUBLE PRECISION) BETWEEN 6 AND 7.5\nAND extract(EPOCH from assessment_date::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  },
  {
   "title": "High Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 62 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(*) FROM vaaas_reports\nWHERE CAST(cvss_score AS DOUBLE PRECISION) > 7.5\nAND extract(EPOCH from assessment_date::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds};"
    }
   ]
  }
 ]
}