{
 "title": "Security Information and Event Management",
 "tags": [
  "SIEM",
  "Security Information and Event Management"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<script type=\"text/javascript\" language=\"javascript\">\r\nfunction goToPage() {\r\n    window.open('https://volos.172.26.7.181.nip.io/siem?ticket=' + window.localStorage.getItem('sphinx_sm_ticket') || '');\r\n}\r\n</script>\r\n<div style=\"padding-top: 20px;\">\r\n    <p style=\"font-size: 35px; text-align: center;\"><b style=\"color: #00a79d;\">SPHINX</b> - Security Information and Event Management</p>\r\n    <hr>\r\n    <div style=\"text-align: center;\">\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/SIEM/SIEM_DASHBOARD_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Dashboard manual</a>\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/SIEM/SIEM_COMPONENT_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Component manual</a>\r\n    <div onclick=\"goToPage()\"  style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    SIEM Webpage\r\n    </div>\r\n    </div>\r\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:437",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:435", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Functionalities",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\n<h2>Short description</h2>\n<p style=\"text-align: justify\">The SIEM component is responsible for triggering alerts and to match information using log files that are collected from multiple resources such as data collected from Data traffic monitoring, system log files, auditing checks, vulnerability assessments.</p>\n<hr/>\n<h2>Objectives</h2>\n<ul style=\"list-style-type: none; padding: 0; margin: 0;\">\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green; font-size:20px;font-weight:bold;\">*</span> Monitors the events created from the log files</li>\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green; font-size:20px;font-weight:bold;\">*</span> Triggers alerts</li>\n</ul>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Low Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT CASE \r\n\tWHEN TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '${__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(low) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tWHEN TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '{__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(low) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tUNION\t\r\n\t\t\tselect sum(low) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tELSE\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(low) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(low) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \t\r\n\t\t\tunion\r\n\t\t\tselect sum(low) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(low) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(low) c\r\n\t\t\tfrom certifications_counter_per_sec \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and '${__to:date}' \r\n\t\t) t1)\r\nEND as n;\t\r\n"
    }
   ]
  },
  {
   "title": "Total Medium Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT CASE \r\n\tWHEN TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '${__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(medium) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tWHEN TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '{__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(medium) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tUNION\t\r\n\t\t\tselect sum(medium) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tELSE\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(medium) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(medium) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \t\r\n\t\t\tunion\r\n\t\t\tselect sum(medium) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(medium) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(medium) c\r\n\t\t\tfrom certifications_counter_per_sec \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and '${__to:date}' \r\n\t\t) t1)\r\nEND as n;\t\r\n"
    }
   ]
  },
  {
   "title": "Total High Vulnerabilities",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT CASE \r\n\tWHEN TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '${__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(high) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tWHEN TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') > '{__to:date}' THEN\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(high) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tUNION\t\r\n\t\t\tselect sum(high) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t) t1)\r\n\tELSE\r\n\t\t(select sum(c) \r\n\t\tfrom (\r\n\t\t\tselect sum(high) c \r\n\t\t\tfrom certifications_counter_per_sec\r\n\t\t\twhere timestamp between '${__from:date}' and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(high) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__from:date}' + (60 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \t\r\n\t\t\tunion\r\n\t\t\tselect sum(high) c\r\n\t\t\tfrom certifications_counter_per_day \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__from:date}' + (1440 * interval '1 minute')), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(high) c\r\n\t\t\tfrom certifications_counter_per_hour \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('day', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') \r\n\t\t\tunion\r\n\t\t\tselect sum(high) c\r\n\t\t\tfrom certifications_counter_per_sec \r\n\t\t\twhere timestamp between TO_CHAR(DATE_TRUNC('hour', TIMESTAMP '${__to:date}'), 'YYYY-MM-DD\"T\"HH24:mi:SS.MS\"Z\"') and '${__to:date}' \r\n\t\t) t1)\r\nEND as n;\t\r\n"
    }
   ]
  },
  {
   "title": "Internal Vulnerabilities",
   "type": "table",
   "description": "10000 limit",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \"AGENT_NAME\", \"AGENT_IP\", \"SEVERITY\", \"RULE_DESCRIPTION\", \"RULE_LEVEL\", \"CVSS3\", \"COUNT\", \"LAST_SEEN\", \"RULE_GROUPS\", \"DATA_SCA_PASSED\", \"DATA_SCA_SCORE\", \"DATA_SCA_FAILED\", \"CVSS3_BASE_SCORE\"\nFROM \"kafka_CERTIFICATIONS_AVRO\"\nWHERE \"START_TIME\" BETWEEN '${__from:date}' AND '${__to:date}'\nAND cast(\"RULE_LEVEL\" AS int) >= 0\nlimit 10000;"
    }
   ]
  },
  {
   "title": "Certifications",
   "type": "table",
   "description": "10000 limit",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT \n\"ALERTID\", \"NAME\", \"START_TIME\", \"END_TIME\", \"QUERY_USED\", \"TAG\", \"RISK_SCORE\", \"SEVERITY\", \"UUID\", \"AGENT_NAME\", \"AGENT_IP\", \"RULE_DESCRIPTION\", \"RULE_LEVEL\", \"CVSS3\", \"COUNT\", \"LAST_SEEN\", \"RULE_GROUPS\", \"DATA_SCA_PASSED\", \"DATA_SCA_SCORE\", \"DATA_SCA_FAILED\", \"CVSS3_BASE_SCORE\"\nFROM \"kafka_CERTIFICATIONS_AVRO\"\nWHERE \"START_TIME\" BETWEEN '${__from:date}' AND '${__to:date}'\nAND cast(\"RULE_LEVEL\" AS int) >= 0\nlimit 10000;"
    }
   ]
  }
 ]
}