{
 "title": "Anomaly Detection",
 "tags": [
  "AD",
  "Anomaly Detection"
 ],
 "time": { "from": "2021-10-20T00:00:00.000Z", "to": "2021-10-28T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Algorithm_type",
    "label": "Algorithm Type",
    "query": "VerticalPortScan_sflow,UDPAmplifier_sflow,SMTPTalker_sflow,P2PCommunication_sflow,MediaStreamingClient_sflow,ICMPTunnel_sflow,HorizontalPortScan_sflow,DnsTunnel_sflow,CCBotNet_sflow,AtypicalTCPPortUsed_sflow,AtypicalNumberOfPairs_sflow,AtypicalAmountData_sflow,AtypicalAlienTCPPortUsed_sflow,AlienAccessingManyHosts_sflow,AbusedSMTP_sflow"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<script type=\"text/javascript\" language=\"javascript\">\r\nfunction goToPage() {\r\n    window.open('https://polaris.146.124.106.181.nip.io/id-ui/ad?ticket=' + window.localStorage.getItem('sphinx_sm_ticket') || '');\r\n}\r\n</script>\r\n<div style=\"padding-top: 20px;\">\r\n    <p style=\"font-size: 35px; text-align: center;\"><b style=\"color: #00a79d;\">SPHINX</b> - Anomaly Detection</p>\r\n    <hr>\r\n    <div style=\"text-align: center;\">\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/AD/AD_DASHBOARD_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Dashboard manual</a>\r\n    <a href=\"/interactive-dashboards/public/manuals/with_dashboards/AD/AD_COMPONENT_MANUAL.pdf\" target=\"_blank\" style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    <img class=\"valign\" src=\"/interactive-dashboards/public/img/pdf.png\" width=\"24px\" height=\"19px\"> Component manual</a>\r\n    <div onclick=\"goToPage()\"  style=\"background-color: teal; border: none; color white; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; cursor: pointer; margin: 4px 2px; color: white;\">\r\n    AD Webpage\r\n    </div>\r\n    </div>\r\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:437",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:435", "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Functionalities",
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "\n<h2>Short description</h2>\n<p style=\"text-align: justify\">Anomaly Detection is a SPHINX component that raises alerts when anomalous or suspicious activities are detected. AD does not use the raw network data. AD uses as input the logs generated by Data Traffic Monitoring component. </p>\n<hr/>\n<h2>Objectives</h2>\n<ul style=\"list-style-type: none; padding: 0; margin: 0;\">\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green;font-size:20px;font-weight:bold;\">*</span> Detect anomalous activities</li>\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green;font-size:20px;font-weight:bold;\">*</span> Analyse HTTP & DNS Traffic with k-means algorithm</li>\n  <li style=\"margin-top: -1px; padding: 12px;\"><span style=\"color: green;font-size:20px;font-weight:bold;\">*</span> Identify issues (SMTP, UDP, P2P, etc.) with statistical algorithms</li>\n</ul>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<h1 style=\"background-color: #00a79d; color: white; padding: 20px\"> Alerts </h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of alerts today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM sphinx.\"kafka_AD_ALERT_AVRO\"  where DATE(\"TIMESTAMP\") >= CURRENT_DATE AND DATE(\"TIMESTAMP\") < CURRENT_DATE + INTERVAL '1 DAY' AND \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[]);"
    }
   ]
  },
  {
   "title": "Number of alerts yesterday",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM sphinx.\"kafka_AD_ALERT_AVRO\" where DATE(\"TIMESTAMP\") = CURRENT_DATE - INTEGER '1' AND \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[]);"
    }
   ]
  },
  {
   "title": "Number of alerts two days ago",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM sphinx.\"kafka_AD_ALERT_AVRO\" where DATE(\"TIMESTAMP\") = CURRENT_DATE - INTEGER '2' AND \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[]);"
    }
   ]
  },
  {
   "title": "Number of alerts per day",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "No. of alerts" }
   ],
   "targets": [
    {
     "rawSql": "SELECT COUNT(*), DATE(\"TIMESTAMP\")::date as time FROM sphinx.\"kafka_AD_ALERT_AVRO\" \nWHERE extract(EPOCH from \"TIMESTAMP\"::timestamp) BETWEEN ${__from:date:seconds} AND ${__to:date:seconds}\nAND \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[]) GROUP BY (time) ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "Short Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \"ALERTID\" AS \"STIX ID\", \"TIMESTAMP\" AS \"Timestamp\", \"TITLE\" AS \"Description\", \"TEXT\" AS \"Details\", \"ALGORITHMSTRINGFLOWS\" AS \"Info\", \"ALGORITHMMYIP\" AS \"IP\", \"ALGORITHMPORTS\" AS \"Ports\", \"FLOWID\" AS \"Flow ID\" FROM sphinx.\"kafka_AD_ALERT_AVRO\" WHERE \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[])\nAND \"TIMESTAMP\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT * FROM sphinx.\"kafka_AD_ALERT_AVRO\" WHERE \"ALGORITHMTYPE\" = ANY(ARRAY[$Algorithm_type]::varchar[])\nAND \"TIMESTAMP\"::timestamp BETWEEN to_timestamp(${__from:date:seconds}) AND to_timestamp(${__to:date:seconds})\nLIMIT 100;"
    }
   ]
  }
 ]
}